### ISSUE TITLE
'Jump To' search doesn't seem to work with vimflowy enabled

### ISSUE THREAD

**Issue by MattHulse** [Wojnach/vimflowy#13]
Cmd + K triggers a 'Jump To' navigation shortcut allowing search terms to be used to select a bullet to jump to.  

I've found that If vimflowy is in INSERT mode, the Jump To search box works.  However, if in NORMAL mode, the behavior is erratic.  Only certain characters can be typed, unable to delete or escape.  Must use the mouse to click outside of the dialog box to get it to go away.

The following console error appears while trying to use the Jump To search box from NORMAL mode:
![image](https://user-images.githubusercontent.com/56975/110866088-d7550f00-8281-11eb-9bd4-e30eb804c25c.png)

On a semi-related note, when in NORMAL mode, the Cmd+? shortcut to show keyboard shortcuts does not work.

**Comment by Wojnach** [comment]
It should be fixed now! Please try it out and let me know if it works :) 

I added support for "cmd-k" binding in the following commit 041162c. The chrome extension should be updated as well.

It's very possible that most 'cmd-' bindings are broken on MAC. Please let me know if you find more. 

Vimflowy doesn't come with any 'cmd-' bindings bound at all. But they can easily be added! The reason why they haven't been added yet is because I don't have any MAC OS to test Vimflowy on.

**Comment by Wojnach** [comment]
Binding 'cmd-?' or 'ctrl-?' might cause problems... 

There is little consistency when it comes to the original Workflowy keybindings. They change depending on what operatingsystem you are running and what keyboard you are currently using. I suspect perhaps that the keybindings are bound to a certain location on the keyboard rather then a certain Key name. 

That means it's gonna be hard to bind any keys based on assumption alone, because there is little to no pattern to follow when handling the original Workflowy keybindings. This is why I tend to avoid binding any original Workflowy keybindingswhen possible. 

The 'cmd-?' and 'ctrl-?' should still work in INSERT mode though. I was hoping that we could leave it unbound in NORMAL mode. But we can definetely bind it and try it out if you feel that would be useful.

**Comment by Wojnach** [comment]
The problem with "cmd-?" binding is that it's bound to the "cmd-'" on nordic keyboards,  but "cmd-'" triggers a zoom to the workflowy home page on US keyboards... So there would be conflict there. 

Ideally the Vimflowy bindings should be bound the same way as the Workflowy bindings.

**Comment by MattHulse** [comment]
The Cmd+K binding is working great now.  Thank you!  I'm not too concerned about the Cmd-? keybinding.
