### ISSUE TITLE
Tip: How to bind "alt" keybindings on mac

### ISSUE THREAD

**Issue by lawenlerk** [Wojnach/vimflowy#16]
**Background:**
I was having issues using the "alt-j" and "alt-k" commands on Mac to move items up and down. This was due to the default behaviour on Mac to type the characters "∆" and "˚" when pressing alt-j and alt-k respectively.

Initially I tried to edit the keybindings to another combination i.e. "meta-j" and "meta-k", but this conflicted with WorkFlowy's jump menu command.

**Solution:**
I found that you can bind "alt-∆" and "alt-˚" in place of "alt-j" and "alt-k" in keybindings.js, and it works perfectly fine on Mac.

Note: Thanks for working on this extension! I was so happy when I found it.

**Comment by lawenlerk** [comment]
Sorry in advance if I'm supposed to file this elsewhere instead. I'm not sure if it should be a PR or not, but wanted to make sure others were able to find this easily too.

**Comment by Wojnach** [comment]
We'll keep it open until the fix is in :) You can issue a PR and we'll merge it in or I'll fix it sometime during the week. 

I expect a bunch of stuff to be broken on the Mac unfortunately. I haven't been able to test it at all due to not having access to a Mac. But I'll get my hands on one this week so I'll do some testing then!

**Comment by Wojnach** [comment]
Should be fixed in dcbb385
