### ISSUE TITLE
Jump to node

### ISSUE THREAD

**Issue by 8utl3r** [Wojnach/vimflowy#2]
I honestly have no idea if this is possible...but as an idea:

Press a key, say 'f' for example and navigation hints pop up at every line on the page (other letters for hints). So if I'm looking at a long list with lots of nodes I can simply press 'f-v' to jump down to a specified line (the one with the 'v' hint popup in this case). This would super charge movement

**Comment by Wojnach** [comment]
It's a great idea! There is a [vim-plugin](https://github.com/easymotion/vim-easymotion) which does something similar.

I'll have a look and see if I can figure out a clean implementation. 

It was actually one of first features I considered adding when reviving the project. But my theoretical implementation of the feature, at the time, depended on workflowys HTML structure -  which was something I wanted to avoid due to it changing over the years. 

What I had in mind was to replace the bullets visually with Letters once you press the key, and the next key would teleport the cursor to that item. 

The most suitable key for the feature, in my opinion, would be SPACE... But it conflicted slightly with the existing workflowy binding CTRL+SPACE, which is why I used it for folding instead. 'f' would be nice but it conflicts with the vim binding 'f' (which might be added in the future). I think the most "safe" binding for now would be CTRL+J?

**Comment by 8utl3r** [comment]
Hi! That's exactly what I was thinking. You can see an implementation on vimflowy.netlify.com as well. 

I honestly don't know how much utility there is in saving Workflowy bindings? Overriding them would certainly be my preference if it's not too hard. :) Space would be perfect. Alt+J or Cmd+J might be a tad better for ergonomics if it needs to a modifier key.

**Comment by Wojnach** [comment]
Implemented in 5d20669

Will be pushed to google chrome store after testing during the week
