### ISSUE TITLE
Normal mode issue with <command>o on mac

### ISSUE THREAD

**Issue by 8utl3r** [Wojnach/vimflowy#6]
When in normal mode if you use the shortcut for show/hide completed items it treats it as if it just pressed "o". The shortcut on mac is <command>"o" so it's likely just not blocking when <command> is pressed.

**Comment by Wojnach** [comment]
Yes, I suspect a lot of stuff is broken for mac users. Workflowy has entirely different keybindings for mac.

I added support for the Cmd key in b5a8fc4eedee1245ef6f10a06e1f1651dd9d6f0b

You can try to use that to solve the problem. Bind stuff to Cmd by typing `meta-`. So `cmd-o` would by bound by typing `meta-o`. I can't fix the problem unfortunately because I can't test it afterwards.

The show/hide completed items shortcut shouldn't theoretically need to be handled though. The shortcut seems to be bound to `ctrl-o` on Windows but on mac it is `cmd-o`? What happens if you use Cmd-o in the browser when typing (while you aren't at workflowy.com), will it still type out `o`?

**Comment by Wojnach** [comment]
I think I maybe figured out what the problem was...

I submitted a fix for it in 24f099fd23479125776488497e6dc64c7de8cfef

If it still doesn't work then you can prevent `o` from being typed out by adding the following to Transparentkeybinding.as:
`
	  'meta-o': e => 
	  {
              e.preventDefault();
	  },
` 
or maybe
`
	  'meta-O': e => 
	  {
              e.preventDefault();
	  },
` 

but with the recent fix I suspect you shouldn't need to
