### ISSUE TITLE
add support for transclusion

### ISSUE THREAD

**Issue by 8utl3r** [Wojnach/vimflowy#9]
the most recent beta has included transclusion (finally...), I was wondering how hard it would be to add support for that via the vimflowy extension. I was thinking something like 'yc' or 'cc' for clone? or even 'cd' for clone then immediately delete clone and add it to clipboard then 'p' to place clone via clipboard.

**Comment by Wojnach** [comment]
ah yeah the "mirror" feature! Interesting. If they've exposed an API function for it then it should be trivial to implement. I'll take a look at it in the coming weeks.

**Comment by 8utl3r** [comment]
I've been asking (because I want to contribute) but where do you find out stuff about the API? No one has given me an answer yet. :( This would be a great project for me to learn/practice. Just a single feature add that should be easy.  

And frankly, I'm worried you'll get bored maintaining this project in a few years and if I haven't figured it out by then I'll lose my amazing set up! That'd be terrible. I do it for speed and to save my hands as long as possible (along with a gergoplex keyboard from gboards.ca, that man is legend).

**Comment by 8utl3r** [comment]
Nvm, I got ahold of the API. Looks like there isn't an exposed function yet for transclusion sadly. I emailed support@workflowy.com and asked them to add it. We'll see how long that takes.

**Comment by Wojnach** [comment]
I usually inspect the available source code itself to figure out how to work with the exposed functions. You can get a readable version of it by:

1. navigating to beta.workflowy.com
2. Press F12
3. Go to the "Sources" Tab
4. Look through the tree on the left side. You should be able to find workflowy .js files over there.

Here is the current direct link to the compressed .min .js file which you'll probably find:
https://beta.workflowy.com/media/js/document_view.min.js?v=0544ddb

Beautify the code by pasting it into https://beautifier.io/
Then copy paste the beautified code into your favorite editor. I recommend SublimeText for this because the file is very big, ~90000 lines. Then just search for the things you need! 

They started documenting the exposed API function here:
https://workflowy.com/s/workflowy-extension-api/6ziauXitmUj7idN2

But I doubt that it is up to date

**Comment by Wojnach** [comment]
I skimmed through the latest source code and it seems to be quite easy to patch together something to make the mirroring work with Vimflowy. 

They mirror items by setting a newly created items name to "mirror/" + MirroredItem.getID()

So the pseudo code would be 
ItemWhichWeWantToMirror = WF.focusedItem()
WF.CreateItem()
NewItemName = "mirror/" + ItemWhichWeWantToMirror.getID()
WF.EditItemName(NewItemName)

And that is probably it :)

**Comment by Wojnach** [comment]
the mirroring is currently ony available in beta.workflowy.com though, so I think it might be good idea to wait with binding it until they add it to workflowy.com -- or atleast until we get Vimflowy working with beta.workflowy.com.

**Comment by Wojnach** [comment]
I appreciate any help I can get! :) I rarely have time to add features to the extension nowaday. The project started of as a procrastination project, for another project 😅 It was never supposed to get this 'big'. Ideally you'd rewrite the extension at this point to make it work as vim does. 

Feel free to add any vim bindings you like, or new bindings specific to vimflowy itself (as long as they don't steal a reserved vim binding) :)

**Comment by MattHulse** [comment]
The latest beta now uses '((' leader to mirror a node inline (similarly '[[' for links).  This functionality makes working with mirrors a dream.  With this addition, do you still think that a vimflowy keybinding would be needed @8utl3r?

**Comment by Wojnach** [comment]
yeah I agree, using '((' and '[[' is really nice! I guess we don't need a specific binding for it. Although yanking and pasting a mirror should perhaps result in a mirror being pasted. I'll look into it.
